Controllers/MyPurchaseController.cs
using CATeam5Solution.Method;
using CATeam5Solution.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CATeam5Solution.Controllers
{
    public class MyPurchaseController : Controller
    {
       private DBContext dbContext;
        public MyPurchaseController(DBContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            

            Session session = GetSession();
            if (session == null)
            {
                return RedirectToAction("Index", "Login");
            }

            Guid userid = session.UsersId;
          
            GetMyPurchaseData myPurchaseMaker = new GetMyPurchaseData(userid, dbContext);
            List<MyPurchaseViewModel> myPurchaseViewModels = myPurchaseMaker.MakeMyPurchaseView();
            ViewData["myPurchaseViewModel"] = myPurchaseViewModels;

            return View();
        }     
        
        private Session GetSession()
        {
            if (Request.Cookies["SessionId"] == null)
            {
                return null;
            }

            Guid sessionId = Guid.Parse(Request.Cookies["SessionId"]);
            Session session = dbContext.Session.FirstOrDefault(x =>
                x.Id == sessionId
            );

            return session;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Adob3 Reseller</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
          
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    Hello,
                    @{
                        @if (Context.Request.Cookies["Username"] != null)
                        {@Context.Request.Cookies["Username"]}
                    else
                    {@: Guest
                    }
                    }
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @if ((string)ViewData["Title"] != "View Cart")
                            {
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><b>Shop</b></a>
                            }
                            else
                            {
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><b>&#8592 Continue Shopping</b></a>
                            }
                        </li>
                        <li class="nav-item">
                                <a class="nav-link light" asp-area="" asp-controller="MyPurchase" asp-action="Index"><b>My Purchases</b></a>
                        </li>


                    <li class="nav-item ml-auto" id="Cart">
                        @*Shopping Cart Icon*@
                        @if ((string)ViewData["Title"] == "View Cart")
                        {
                            <a></a>
                        }
                        else
                        {
                             <a asp-controller="Cart" asp-action="ViewCart">
                            <svg xmlns="http://www.w3.org/2000/svg" width="30" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                                <span id="CartCount" class="position-absolute top-5 start-90 translate-middle badge border border-light rounded-circle bg-danger p-2"><span class="visually-hidden"></span></span>
                            </svg>
                        </a>
                        }
                    </li>
                        <li class="nav-item text-light" style="margin-left:20px">
                           
                            @{
                                @if (Context.Request.Cookies["SessionId"] != null)
                                {
                                    <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Logout"><b>Logout</b></a>
                                }
                                else
                                { <span class="glyphicon glyphicon-envelope"></span>
                                    <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index"><b>Login</b></a>
                                }
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @*header banner*@
    <section style=" width: 100%; padding: 20px 0; text-align: center; background-color: royalblue; color: white; margin: 0">
        <h2><img src="/img/Logo.png" style="height:100px; width: 100px; padding: 20px;"/>Adob3 Reseller</h2>
        @if ((string)ViewData["Title"] == "Home Page")
        {
            <h1>Shop</h1>
        }
        else if ((string)ViewData["Title"] == "View Cart")
        {
            <h1>Shopping Cart</h1>
        }
        else if ((string)ViewData["Title"] == "About")
        {
            <h1>About</h1>
        }
        else if ((string)ViewData["Title"] == "My Purchases")
        {
            <h1>My Purchases</h1>
        }
        else
        {
            <h1></h1>
        }
    </section>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-light">
            &copy; 2021 - Adob3 Reseller - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
        </div>
    </footer>

    <div class="container">
        <main role="main" class="pb-3">
            @if (@TempData["Pop"] != null) 
            {
                <script>
                    var message = '@TempData["Pop"]';
                    alert(message);
                </script>
            }
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>